# Generated by Django 4.2.5 on 2023-10-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StyleCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameStyle', models.CharField(max_length=50, verbose_name='Название')),
                ('codeStyle', models.TextField(verbose_name='Код')),
                ('dateCreation', models.DateField(verbose_name='Дата создания карточки')),
            ],
            options={
                'verbose_name': 'Карточка стиля',
                'verbose_name_plural': 'Карточки стилей',
            },
        ),
    ]
